In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_1d.shape, arr_2d.shape)

arr3 = arr_1d + arr_2d
print(arr3.shape, arr3)

(3,) (2, 3)
(2, 3) [[2 4 6]
 [5 7 9]]


In [5]:
x = np.array([[1],[2],[3]])
y = np.array([10, 20, 30])

print(x + y)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
