In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [17]:
arr_1d = np.array([1, 2, 3, 4, 5])
zeros = np.zeros((2,3), dtype=np.float32)
arange = np.arange(0, 10, 2)
linespace = np.linspace(0, 1, 5)
randn = np.random.randn(3,3)

In [18]:
print("arr_1d\n", arr_1d)
print("zeros\n", zeros)
print("arange\n", arange)
print("linespace\n", linespace)
print("randn\n", randn)


arr_1d
 [1 2 3 4 5]
zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
arange
 [0 2 4 6 8]
linespace
 [0.   0.25 0.5  0.75 1.  ]
randn
 [[ 0.89019411  0.26538958  0.38901387]
 [-1.56089751 -1.59939525  0.96342855]
 [-1.40915432  0.32747229 -0.83272069]]


In [21]:
M = np.array([
    [10, 20, 30],
    [10, 50, 60],
    [70, 80, 90]
])

print("Duas primeiras linhas", M[:2 :])
print("Duas primeiras colunas", M[:, :2])
print("Elemento [1, 2]: ", M[1,2])

Duas primeiras linhas [[10 20 30]
 [10 50 60]]
Duas primeiras colunas [[10 20]
 [10 50]
 [70 80]]
Elemento [1, 2]:  60


In [22]:
mask = M > 50
print("Elementos > 50 (1D): ", M[mask])

Elementos > 50 (1D):  [60 70 80 90]


In [23]:
rows = [0, 2]
cols = [1, 2]
print("Fancy indexing [0,1] e [2,2]: ", M[rows, cols])

Fancy indexing [0,1] e [2,2]:  [20 90]
